# Generated by Django 4.1.4 on 2023-01-11 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('author', models.TextField(verbose_name='Автор')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка')),
                ('read_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прочтения')),
                ('format_read', models.CharField(choices=[('C', 'classic'), ('A', 'audio')], max_length=1)),
                ('is_on_shelf', models.BooleanField(default=False, verbose_name='На полке')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-id'],
            },
        ),
    ]
