# Generated by Django 4.1.4 on 2023-02-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_application_remove_post_cat_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
